version: 2
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test client
          command: |
            export CI=true
            docker build -t ${DOCKERHUB_PASSWD}/docker_k8s_multi_aws_client -f ./client/Dockerfile.dev ./client
            docker run -it ${DOCKERHUB_PASSWD}/docker_k8s_multi_aws_client npm run test -- --coverage --watchAll=false
  publish-latest:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build client image
          command: |
            docker build -t ${DOCKERHUB_PASSWD}/multi-client ./client
            docker build -t ${DOCKERHUB_PASSWD}/multi-nginx ./nginx
            docker build -t ${DOCKERHUB_PASSWD}/multi-server ./server
            docker build -t ${DOCKERHUB_PASSWD}/multi-worker ./worker
      - deploy:
          name: Push application Docker image
          command: |
            echo "$DOCKERHUB_SHADOW" | docker login -u "$DOCKERHUB_PASSWD" --password-stdin
            docker push ${DOCKERHUB_PASSWD}/multi-client
            docker push ${DOCKERHUB_PASSWD}/multi-nginx
            docker push ${DOCKERHUB_PASSWD}/multi-server
            docker push ${DOCKERHUB_PASSWD}/multi-worker
            
workflows:
  version: 2
  build-master:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - test
          filters:
            branches:
              only: main