version: 2
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test client
          command: |
            cd client
            export CI=true
            docker build -t ${DOCKERHUB_PASSWD}/docker_k8s_multi_aws_client -f Dockerfile.dev .
            docker run -it ${DOCKERHUB_PASSWD}/docker_k8s_multi_aws_client npm run test -- --coverage --watchAll=false
  publish-latest:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build client image
          command: |
            docker build -t ${DOCKERHUB_PASSWD}/docker_k8s_aws .
      - deploy:
          name: Push application Docker image
          command: |
            cd client
            echo "$DOCKERHUB_SHADOW" | docker login -u "$DOCKERHUB_PASSWD" --password-stdin
            docker push ${DOCKERHUB_PASSWD}/docker_k8s_multi_aws_client
workflows:
  version: 2
  build-master:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - publish-latest:
          requires:
            - test
          filters:
            branches:
              only: main